package com.careerit.cj.day2;

import java.util.Random;
import java.util.Scanner;

public class DiceGame {

  public static void main(String[] args) {

    // 6 faces of dice, so the number will be from 1 to 6, we need to ask the user to guess the number if
    // the guessed number is same as the number generated by the computer then the message should be "You won"
    // else "You lost" and also print the number generated by the computer.

    Random random = new Random();
    int generatedNumber = random.nextInt(6) + 1;  // Generates a number between 1 and 6

    Scanner sc = new Scanner(System.in);
    System.out.println("Guess the number between 1 and 6:");
    int guessedNumber = sc.nextInt();

    if(guessedNumber == generatedNumber) {
      System.out.println("You won");
    }else {
      System.out.println("You lost");
      System.out.println("The number is :"+generatedNumber);
    }
  }
}
